import { Providers } from "@/components/theme/Providers";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { KeyboardShortcutsProvider } from "./context/KeyboardShortcutsContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Flow — Clear your mind through expressive writing",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.className}, mx-auto container dark:bg-black`}>
        <Providers>
          <KeyboardShortcutsProvider>{children}</KeyboardShortcutsProvider>
        </Providers>
      </body>
    </html>
  );
}
